botApikey: botApikey-test

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uos-reataurant-bot-db?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=1000
    username: root
    password: rhfelfkrtm!23
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

logging:
  level:
    org.hibernate.SQL: DEBUG