package seaung.uoscafeteriamenu.domain.entity;

public enum BlockName {
    STUDENT_HALL_BREAKFAST,
    MAIN_BUILDING_BREAKFAST,
    WESTERN_RESTAURANT_BREAKFAST,
    MUSEUM_OF_NATURAL_BREAKFAST,

    STUDENT_HALL_LUNCH,
    MAIN_BUILDING_LUNCH,
    WESTERN_RESTAURANT_LUNCH,
    MUSEUM_OF_NATURAL_LUNCH,

    STUDENT_HALL_DINNER,
    MAIN_BUILDING_DINNER,
    WESTERN_RESTAURANT_DINNER,
    MUSEUM_OF_NATURAL_DINNER,

    MENU_RECOMMEND
}
